### PR TITLE
Check if SymfonyHttplug actually implements HttpClient

### LINKED ISSUE #252: Symfony 7 no longer implements Http\Client\HttpClient
**Description**
symfony/http-client no longer implements Http\Client\HttpClient so discovery should not return it.

**How to reproduce**
run 
```php
<?php
var_dump(\Http\Discovery\HttpClientDiscovery::find() instanceof  Http\Client\HttpClient); // false
```
with symfony/http-client v7 installed

### PR DESCRIPTION
**Pull request by arokettu**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #252
| License         | MIT

#### What's in this PR?

When looking for HttpClient, check if SymfonyHttplug actually implements HttpClient.

#### Why?

In Symfony 7, SymfonyHttplug no longer implements HttpClient

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

### CODE REVIEW

File: src/Strategy/CommonClassesStrategy.php [hunk 1]
```diff
@@ -158,6 +158,11 @@ public static function isGuzzleImplementingPsr18()
         return defined('GuzzleHttp\ClientInterface::MAJOR_VERSION');
     }
 
+    public static function isSymfonyImplementingHttpClient()
```
Comment (nicolas-grekas) [inline src/Strategy/CommonClassesStrategy.php:161]:
```suggestion
    public static function isSymfonyImplementingHttplug()
```

File: src/Strategy/CommonClassesStrategy.php [hunk 2]
```diff
@@ -158,6 +158,11 @@ public static function isGuzzleImplementingPsr18()
...
+    {
+        return is_a(SymfonyHttplug::class, HttpClient::class, true);
```
Comment (nicolas-grekas) [inline src/Strategy/CommonClassesStrategy.php]:
```suggestion
        return is_subclass_of(SymfonyHttplug::class, HttpClient::class);
```

File: src/Strategy/CommonClassesStrategy.php (hunk 1 above)
Comment (arokettu) [reply src/Strategy/CommonClassesStrategy.php:161]: HttpAsyncClient is kinda Httplug too

**Review by dbu — APPROVED** [review]
thanks a lot for this one.

File: src/Strategy/CommonClassesStrategy.php (hunk 1 above)
Comment (dbu) [reply src/Strategy/CommonClassesStrategy.php:161]: i agree with @arokettu 

its not going to be relevant forever, we deprecated the synchronous php-http HttpClient interface in favor of the PSR18 http client. only the async php-http client is still relevant. when we do a new major of discovery, we will drop discovering HttpClient.

**Comment by dbu** [comment]
https://github.com/php-http/discovery/releases/tag/1.19.2
