### PR TITLE
PSR-17 should be available to use Symfony's HttplugClient

### LINKED ISSUE #149: Auto discovery broken in Symfony 4.4 ?
After upgrading to Symfony 4.4, I got the following error:

`bin/console`

image

Stack trace:

```
[Http\Discovery\Exception\ClassInstantiationFailedException]  
  Unexpected exception when instantiating class

  at vendor/php-http/discovery/src/ClassDiscovery.php:210
 Http\Discovery\ClassDiscovery::instantiateClass() at vendor/php-http/discovery/src/HttpClientDiscovery.php:34
 Http\Discovery\HttpClientDiscovery::find() at vendor/friendsofapi/localise.biz/src/HttpClientConfigurator.php:59
 FAPI\Localise\HttpClientConfigurator->__construct() at var/cache/dev/ContainerBZs79FG/getPhpTranslation_Adapter_LocoService.php:17
 require() at var/cache/dev/ContainerBZs79FG/srcApp_KernelDevDebugContainer.php:742
 ContainerBZs79FG\srcApp_KernelDevDebugContainer->load() at var/cache/dev/ContainerBZs79FG/getPhpTranslation_Storage_WdaService.php:16
 require() at var/cache/dev/ContainerBZs79FG/srcApp_KernelDevDebugContainer.php:742
 ContainerBZs79FG\srcApp_KernelDevDebugContainer->load() at var/cache/dev/ContainerBZs79FG/getPhpTranslation_StorageManagerService.php:13
 require() at var/cache/dev/ContainerBZs79FG/srcApp_KernelDevDebugContainer.php:742
 ContainerBZs79FG\srcApp_KernelDevDebugContainer->load() at var/cache/dev/ContainerBZs79FG/getPhpTranslator_Console_DeleteObsoleteService.php:15
 require() at var/cache/dev/ContainerBZs79FG/srcApp_KernelDevDebugContainer.php:742
 ContainerBZs79FG\srcApp_KernelDevDebugContainer->load() at vendor/symfony/dependency-injection/Container.php:444
 Symfony\Component\DependencyInjection\Container->getService() at vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40
 Symfony\Component\DependencyInjection\Argument\ServiceLocator->get() at vendor/symfony/console/CommandLoader/ContainerCommandLoader.php:45
 Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get() at vendor/symfony/console/Application.php:542
 Symfony\Component\Console\Application->has() at vendor/symfony/console/Application.php:743
 Symfony\Component\Console\Application->all() at vendor/symfony/framework-bundle/Console/Application.php:143
 Symfony\Bundle\FrameworkBundle\Console\Application->all() at vendor/symfony/console/Descriptor/ApplicationDescription.php:91
 Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication() at vendor/symfony/console/Descriptor/ApplicationDescription.php:68
 Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands() at vendor/symfony/console/Descriptor/TextDescriptor.php:202
 Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication() at vendor/symfony/console/Descriptor/Descriptor.php:55
 Symfony\Component\Console\Descriptor\Descriptor->describe() at vendor/symfony/console/Helper/DescriptorHelper.php:67
 Symfony\Component\Console\Helper\DescriptorHelper->describe() at vendor/symfony/console/Command/ListCommand.php:75
 Symfony\Component\Console\Command\ListCommand->execute() at vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:1029
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/framework-bundle/Console/Application.php:100
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at bin/console:36
```

Related packages I have installed:

```
php-http/guzzle6-adapter
php-translation/symfony-bundle
php-translation/loco-adapter
```

I fixed it by installing `http-interop/http-factory-guzzle` but I wonder what has changed in Symfony 4.4 that broke the http discovery?

### PR DESCRIPTION
**Pull request by mbabker**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #149
| Documentation   | N/A
| License         | MIT

#### What's in this PR?

This is a bit of a stab in the dark, but I ran into the same problem in that issue and it seems like this PR should fix it.

Since #141 Symfony's `Symfony\Component\HttpClient\HttplugClient` is the first client class attempted when using auto-discovery, with its only condition being that that specific class is available (which is true if you have `symfony/http-client >=4.4` installed).  However, if you don't have anything which satisfies the PSR-17 auto discovery installed, then auto-discovery as a whole is going to fail because the Symfony class can't be instantiated.

This PR attempts to fix the issue by adding a condition on the PSR-17 interfaces being present as well.  Looking at the Symfony app where I ran into the problem (Symfony 3.4 with the HttpClient component being pulled in as a transient dependency at 4.4), it seems like this would fix the problem because through that application's transient dependencies PSR-17 isn't installed so this condition should fail and it fall through to a working client (Guzzle in this application's case).

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do

- [ ] Is this the right way to address this issue?

### CODE REVIEW

**Comment by XWB** [comment]
I can confirm that this change fixes https://github.com/php-http/discovery/issues/149

**Comment by garak** [comment]
What about HttpAsyncClient? It should discover Symfony HttpClient too

File: src/Strategy/CommonClassesStrategy.php [hunk 1]
```diff
@@ -72,7 +73,7 @@ final class CommonClassesStrategy implements DiscoveryStrategy
             ['class' => React::class, 'condition' => React::class],
         ],
         HttpClient::class => [
-            ['class' => SymfonyHttplug::class, 'condition' => SymfonyHttplug::class],
+            ['class' => SymfonyHttplug::class, 'condition' => [SymfonyHttplug::class, Psr17RequestFactory::class]],
```
Comment (xabbuh) [inline src/Strategy/CommonClassesStrategy.php]: Won't this possibly break applications using HttpClient 4.3 where this was not necessary?

Comment (mbabker) [reply src/Strategy/CommonClassesStrategy.php]: The `HttplugClient` class that this is checking for doesn't exist in HttpClient 4.3 so it shouldn't be an issue.

**Comment by Nyholm** [comment]
Ooops. I was too quick. It should be the message factory from HTTPlug.

**Comment by XWB** [comment]
It looks like the fix was reverted by https://github.com/php-http/discovery/commit/4257709f3cb092aba756430b0c32e498fbda6545

Symfony 4.4 is still broken!

**Comment by dbu** [comment]
did you try with discovery 1.7.2? we had to fix checks to also look at interfaces and not only classes.
